# Generated by Django 5.0 on 2023-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaitonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uername', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
    ]
