# Generated by Django 5.0 on 2023-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediation_app', '0002_rename_uername_mediaitonprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('album', models.CharField(blank=True, max_length=50)),
                ('artist', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
